apiVersion: 1

policies:
  - orgId: 1
    receiver: email-cpd
    group_by: ['alertname', 'sensor_id']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 30m
    routes:
      - receiver: email-cpd
        object_matchers:
          - ['alertname', '=~', 'Sensor CPD sin datos']
        group_by: ['alertname', 'sensor_id']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 24h
